[package]
name = "connectors-build"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
serde_json.workspace = true
serde.workspace = true
serde_yaml_ng.workspace = true
connectors-spec = { path = "../connectors-spec" }
tempfile.workspace = true
