[package]
name = "connectors-build"
version.workspace = true
edition.workspace = true
rust-version = "1.91"
license.workspace = true

[dependencies]
connectors-catalog = { path = "../connectors-catalog" }
connectors-catalog-provider = { path = "../../adapters/catalog", default-features = false }
clap.workspace = true
serde_json.workspace = true
serde.workspace = true
serde_yaml_ng.workspace = true
connectors-spec = { path = "../connectors-spec" }
tempfile.workspace = true
pulldown-cmark = "0.13.4"
regex = "1"
jsonschema.workspace = true
ess-compiler.workspace = true
ess-domain.workspace = true
ess-entity-runtime.workspace = true
ess-service-contract.workspace = true
ess-synth.workspace = true
