//! The website's executable examples and its public-output audit. The reference pages are
//! generated by `connectors-docs`.
use super::Result;
use connectors_spec::v2::{hash, json_bytes};
use serde_json::{Value, json};
use std::{
    collections::{BTreeMap, BTreeSet},
    fs,
    path::{Path, PathBuf},
    process::Command,
};

fn copy_changed(from: &Path, to: &Path) -> Result<()> {
    if from.is_dir() {
        fs::create_dir_all(to)?;
        let mut entries = fs::read_dir(from)?.collect::<std::result::Result<Vec<_>, _>>()?;
        entries.sort_by_key(|entry| entry.file_name());
        for entry in entries {
            copy_changed(&entry.path(), &to.join(entry.file_name()))?;
        }
    } else {
        let bytes = fs::read(from)?;
        if fs::read(to).ok().as_deref() != Some(bytes.as_slice()) {
            fs::write(to, bytes)?;
        }
    }
    Ok(())
}

/// The example targets, each synthesized to `<work>/generated/<target>/connectors`.
const EXAMPLE_TARGETS: [&str; 2] = ["rust", "web"];

/// The domains `website/examples/realization` reads through `connectors_types`. With the
/// domains the example component owns, these are the roots of the example model, which carries
/// them and every domain they reference and nothing else. A domain no example reads is not
/// synthesized for the examples: the CLI presentation domain's `connectors-local/1` variants
/// are a released wire spelling that the Rust target cannot spell as identifiers.
const EXAMPLE_DOMAINS: [&str; 5] = [
    "connectors.mutations",
    "connectors.auth_bindings",
    "connectors.connection_admission",
    "connectors.discovery_state",
    "connectors.idempotency",
];

fn yaml(path: &Path) -> Result<serde_yaml_ng::Value> {
    serde_yaml_ng::from_slice(&fs::read(path)?)
        .map_err(|error| format!("{}: {error}", path.display()).into())
}

fn yaml_strings<'a>(value: &'a serde_yaml_ng::Value, out: &mut Vec<&'a str>) {
    match value {
        serde_yaml_ng::Value::String(text) => out.push(text),
        serde_yaml_ng::Value::Sequence(items) => {
            items.iter().for_each(|item| yaml_strings(item, out))
        }
        serde_yaml_ng::Value::Mapping(map) => map.iter().for_each(|(key, value)| {
            yaml_strings(key, out);
            yaml_strings(value, out);
        }),
        serde_yaml_ng::Value::Tagged(tagged) => yaml_strings(&tagged.value, out),
        _ => {}
    }
}

/// `roots` and every domain they reference, transitively, as domain name -> domain file.
///
/// A domain references another by a qualified name, `<domain>.<Name>`, anywhere in its parsed
/// document; comments are not read. A missing reference is not guessed: ESS validation of the
/// assembled model refuses it.
fn domain_closure(
    domains_dir: &Path,
    roots: &BTreeSet<String>,
) -> Result<BTreeMap<String, PathBuf>> {
    let mut documents = BTreeMap::new();
    for entry in fs::read_dir(domains_dir)? {
        let path = entry?.path();
        let document = yaml(&path)?;
        let name = document["domain"]
            .as_str()
            .ok_or_else(|| format!("{}: no `domain:`", path.display()))?
            .to_owned();
        documents.insert(name, (path, document));
    }
    let mut selected = BTreeMap::new();
    let mut pending: Vec<String> = roots.iter().cloned().collect();
    while let Some(name) = pending.pop() {
        if selected.contains_key(&name) {
            continue;
        }
        let (path, document) = documents
            .get(&name)
            .ok_or_else(|| format!("example domain `{name}` is not declared"))?;
        selected.insert(name, path.clone());
        let mut strings = Vec::new();
        yaml_strings(document, &mut strings);
        for other in documents.keys() {
            let prefix = format!("{other}.");
            if !selected.contains_key(other) && strings.iter().any(|s| s.contains(&prefix)) {
                pending.push(other.clone());
            }
        }
    }
    Ok(selected)
}

/// Copy the canonical model's system into `model`, keeping only the example domains and their
/// references, and the example component in place of the canonical ones.
fn assemble_example_model(root: &Path, model: &Path) -> Result<()> {
    let components_path = root.join("website/examples/components.yaml");
    let mut roots: BTreeSet<String> = EXAMPLE_DOMAINS.iter().map(|d| (*d).to_owned()).collect();
    for component in yaml(&components_path)?["components"]
        .as_sequence()
        .ok_or("website/examples/components.yaml: no `components:`")?
    {
        for domain in component["owns"]["domains"]
            .as_sequence()
            .into_iter()
            .flatten()
        {
            roots.insert(domain.as_str().ok_or("non-text owned domain")?.to_owned());
        }
    }
    let selected = domain_closure(&root.join("ess/domains"), &roots)?;
    let mut system = yaml(&root.join("ess/system.yaml"))?;
    let listed = system["domains"]
        .as_sequence_mut()
        .ok_or("ess/system.yaml: no `domains:`")?;
    listed.retain(|domain| domain.as_str().is_some_and(|d| selected.contains_key(d)));
    if listed.len() != selected.len() {
        return Err("an example domain is not listed in ess/system.yaml".into());
    }
    fs::create_dir_all(model.join("domains"))?;
    fs::write(
        model.join("system.yaml"),
        serde_yaml_ng::to_string(&system)?,
    )?;
    for path in selected.values() {
        copy_changed(
            path,
            &model
                .join("domains")
                .join(path.file_name().ok_or("domain file has no name")?),
        )?;
    }
    copy_changed(&components_path, &model.join("components.yaml"))
}

/// Assemble the disposable example model under `work` and synthesize it for every example
/// target. Returns `<work>/generated`. The canonical domains are never modified.
pub fn synthesize_examples(root: &Path, ess: &Path, work: &Path) -> Result<PathBuf> {
    let model = work.join("model");
    assemble_example_model(root, &model)?;
    let before = super::run(
        Command::new(ess)
            .args(["specify", "validate", "--path"])
            .arg(&model),
    )?;
    print!("{}", String::from_utf8_lossy(&before.stdout));
    let generated = work.join("generated");
    for target in EXAMPLE_TARGETS {
        super::run(
            Command::new(ess)
                .args(["generate", "synthesize", "--path"])
                .arg(&model)
                .args(["--target", target, "--out"])
                .arg(generated.join(target).join("connectors")),
        )?;
    }
    Ok(generated)
}

/// Assemble a disposable example model without modifying the canonical domains.
pub fn examples(root: &Path, ess: &Path) -> Result<()> {
    check_walkthrough_fixtures(root)?;
    fs::create_dir_all(root.join(".local/tmp"))?;
    let temp = tempfile::Builder::new()
        .prefix("website-examples-")
        .tempdir_in(root.join(".local/tmp"))?;
    let generated = synthesize_examples(root, ess, temp.path())?;
    let dest = root.join("website/.cache/demo");
    fs::create_dir_all(&dest)?;
    for target in EXAMPLE_TARGETS {
        copy_changed(
            &generated.join(target).join("connectors"),
            &dest.join("generated").join(target).join("connectors"),
        )?;
    }
    // Compiler diagnostics in WASM must not disclose workstation paths.
    let mut rust_flags = std::env::var("CARGO_ENCODED_RUSTFLAGS").unwrap_or_else(|_| {
        std::env::var("RUSTFLAGS")
            .unwrap_or_default()
            .split_whitespace()
            .collect::<Vec<_>>()
            .join("\u{1f}")
    });
    for (source, replacement) in [
        (std::env::var_os("HOME").map(PathBuf::from), "/source/user"),
        (Some(root.to_path_buf()), "/source/connectors"),
    ] {
        if let Some(source) = source {
            if !rust_flags.is_empty() {
                rust_flags.push('\u{1f}');
            }
            rust_flags.push_str(&format!(
                "--remap-path-prefix={}={replacement}",
                source.display()
            ));
        }
    }
    // One project-owned cache root, no shared target directory across worktrees.
    let output = super::run(
        Command::new("cargo")
            .current_dir(root)
            .env("CARGO_BUILD_JOBS", "2")
            .env("CARGO_ENCODED_RUSTFLAGS", rust_flags)
            .args([
                "build",
                "--locked",
                "--offline",
                "--release",
                "--target",
                "wasm32-unknown-unknown",
                "--features",
                "browser",
                "--manifest-path",
            ])
            .arg(root.join("website/examples/realization/Cargo.toml"))
            .arg("--target-dir")
            .arg(dest.join("target")),
    )?;
    print!("{}", String::from_utf8_lossy(&output.stderr));
    let wasm = dest.join("target/wasm32-unknown-unknown/release/connectors_contract_examples.wasm");
    let published = root.join("website/static/examples");
    fs::create_dir_all(&published)?;
    copy_changed(&wasm, &published.join("contracts.wasm"))?;
    let catalog = fs::read(dest.join("generated/web/connectors/catalog.json"))?;
    fs::write(published.join("catalog.json"), catalog)?;
    let sources = super::tree(&root.join("ess"))?;
    let manifest = json!({"ess":connectors_spec::toolchain::pin()?.ess,"wasm_digest":hash(&fs::read(wasm)?),"source_files":sources.iter().map(|(name,bytes)|(name.clone(),hash(bytes))).collect::<BTreeMap<_,_>>(),"composition_digest":hash(&fs::read(root.join("website/examples/components.yaml"))?),"scope":"In-memory example behavior; no provider I/O or production persistence"});
    fs::write(published.join("manifest.json"), json_bytes(&manifest)?)?;
    audit(&published)?;
    println!("website: Rust/WASM contract examples built");
    Ok(())
}

fn check_walkthrough_fixtures(root: &Path) -> Result<()> {
    let fixture: Value = serde_json::from_slice(&fs::read(
        root.join("website/examples/walkthrough-fixtures.json"),
    )?)?;
    let descriptor = shipped_gitlab_descriptor(root)?;
    validate_walkthrough_fixtures(&descriptor, &fixture)?;
    println!("website: walkthrough input/result match the shipped GitLab selection");
    Ok(())
}

/// The operations the catalog provider declares for the shipped GitLab
/// selection set against the committed bundle, in descriptor shape.
fn shipped_gitlab_descriptor(root: &Path) -> Result<Value> {
    use connectors_catalog_provider::{Effect, Engine, Selection};
    let shipped: Value = serde_json::from_slice(&fs::read(
        root.join("adapters/catalog/providers/gitlab/operations.json"),
    )?)?;
    let selections: Vec<Selection> = serde_json::from_value(shipped["operations"].clone())?;
    let bundle = connectors_catalog::bundle::load(
        &root.join("adapters/catalog/generated/bundles"),
        "gitlab",
    )
    .map_err(|error| format!("gitlab bundle: {error:?}"))?;
    let engine = Engine::new(&bundle, "/api/v4", &selections)
        .map_err(|error| format!("shipped GitLab selection: {error:?}"))?;
    Ok(json!({"operations": engine.declarations(&[Effect::Read, Effect::Write])}))
}

fn validate_walkthrough_fixtures(descriptor: &Value, fixture: &Value) -> Result<()> {
    let operation = descriptor["operations"]
        .as_array()
        .ok_or("missing descriptor operations")?
        .iter()
        .find(|op| op["id"] == fixture["operation"])
        .ok_or("walkthrough operation is not in the shipped GitLab selection")?;
    for (name, schema) in [("input", "input_schema"), ("result", "output_schema")] {
        let validator = jsonschema::validator_for(&operation[schema])?;
        if !validator.is_valid(&fixture[name]) {
            return Err(
                format!("walkthrough {name} does not match the shipped GitLab selection").into(),
            );
        }
    }
    Ok(())
}

/// Inspect bytes as well as text: WASM can embed diagnostic source paths.
pub fn audit(directory: &Path) -> Result<()> {
    let files = super::tree(directory)?;
    if files.is_empty() {
        return Err("public output is empty".into());
    }
    for (name, bytes) in &files {
        for forbidden in [
            "/home/",
            "/Users/",
            ".local/",
            ".engineering/",
            "docs/evidence/",
        ] {
            if bytes
                .windows(forbidden.len())
                .any(|window| window == forbidden.as_bytes())
            {
                return Err(
                    format!("private path marker {forbidden:?} in public output {name}").into(),
                );
            }
        }
    }
    println!(
        "website: {} public files checked; no private path markers",
        files.len()
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn walkthrough_fixtures_follow_the_shipped_selection() {
        let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
        let descriptor = shipped_gitlab_descriptor(&root).unwrap();
        let fixture: Value = serde_json::from_str(include_str!(
            "../../../website/examples/walkthrough-fixtures.json"
        ))
        .unwrap();
        validate_walkthrough_fixtures(&descriptor, &fixture).unwrap();
        let mut invalid = fixture.clone();
        invalid["input"]["invented"] = json!("value");
        assert!(
            validate_walkthrough_fixtures(&descriptor, &invalid).is_err(),
            "the selection declares no such parameter"
        );
        invalid = fixture.clone();
        invalid["result"]["provenance"]
            .as_object_mut()
            .unwrap()
            .remove("source_revision");
        assert!(validate_walkthrough_fixtures(&descriptor, &invalid).is_err());
        invalid = fixture;
        invalid["operation"] = json!("invented.operation");
        assert!(validate_walkthrough_fixtures(&descriptor, &invalid).is_err());
    }
    /// The `npm run build` examples step: the example model validates and both example
    /// targets synthesize with the pinned ESS.
    #[test]
    fn example_model_synthesizes_for_every_example_target_with_the_pinned_ess() {
        let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
        let ess = connectors_spec::toolchain::resolve(None).unwrap();
        let base = root.join(".local/tmp");
        fs::create_dir_all(&base).unwrap();
        let work = tempfile::Builder::new()
            .prefix("examples-synthesis-")
            .tempdir_in(base)
            .unwrap();
        let generated = synthesize_examples(&root, &ess, work.path()).unwrap();
        for target in EXAMPLE_TARGETS {
            assert!(
                generated.join(target).join("connectors").is_dir(),
                "{target}"
            );
        }
    }
    #[test]
    fn example_model_carries_the_example_domains_and_their_references_only() {
        let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
        let work = tempfile::tempdir().unwrap();
        assemble_example_model(&root, work.path()).unwrap();
        let system = yaml(&work.path().join("system.yaml")).unwrap();
        let listed: BTreeSet<&str> = system["domains"]
            .as_sequence()
            .unwrap()
            .iter()
            .map(|d| d.as_str().unwrap())
            .collect();
        for domain in EXAMPLE_DOMAINS {
            assert!(listed.contains(domain), "{domain}");
        }
        // `connectors.mutations` references `connectors.sessions`; the realization does not.
        assert!(listed.contains("connectors.sessions"));
        assert!(!listed.contains("connectors.cli"));
        assert!(!work.path().join("domains/cli.yaml").exists());
        assert_eq!(
            fs::read_dir(work.path().join("domains")).unwrap().count(),
            listed.len()
        );
    }
    #[test]
    fn public_audit_checks_embedded_binary_paths() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(
            dir.path().join("example.wasm"),
            b"\0asm\0/home/example/private.rs",
        )
        .unwrap();
        assert!(audit(dir.path()).is_err());
        fs::write(
            dir.path().join("example.wasm"),
            b"\0asm\0/source/example.rs",
        )
        .unwrap();
        audit(dir.path()).unwrap();
    }
}
