secret_service_socket = <redacted>
format = "connectors-local/2"
owner_uid = 1000

[adapters]

[approval_clock]
format = "roughtime-clock/1"
address = "192.36.143.134:2002"
public_key = "S3AzfZJ5CjSdkJ21ZJGbxqdYP/SoE8fXKY0+aicsehI="
max_rate_error_ppm = 10000

[adapters.forge]
instance_id = "gitlab-sandbox"
adapter_id = "catalog"
configuration_revision = "46f7e22844c2dfc3462aab35722c7b6a2be4dc0eda2f18819a0417a6d1547bfa"
protocol = "v1alpha1"
private_protocol = "connectors-private/2"
startup = "on-demand"
restart = "never"

[adapters.forge.permissions]
profiles = ["gitlab.pat"]
operations = ["project.get", "issues.list", "file.get", "branch.get", "merge_requests.list", "merge_request.get", "pipelines.list", "pipeline.get", "pipeline.jobs", "job.get", "job.trace", "merge_request.create", "merge_request.update", "merge_request.merge"]

[adapters.forge.executable]
path = "<repo>/target/release/connectors-catalog-provider"
sha256 = "46387422284ff83e347d50055df08270336ccf7d5051e90dd3a667c894fedc56"
args = ["--local-config", "<sandbox>/gitlab-catalog-2.json"]
