[package]
name = "connectors-spec"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
connectors-core.workspace = true
serde.workspace = true
serde_json.workspace = true
jsonschema.workspace = true
clap.workspace = true
serde_yaml_ng.workspace = true
sha2.workspace = true
hex.workspace = true
tempfile.workspace = true

connectors-host = { workspace = true, features = ["schema"] }
