#!/usr/bin/env python3
"""Vendor Runpod's published REST API v2 OpenAPI document.

Runpod serves the document from its own API host rather than from a tagged repository, so there
is no commit to pin: `UPSTREAM_SHA256` is the pin, and an upstream edit fails this script loudly
instead of being absorbed. Re-pinning is a deliberate, reviewable commit (AGENTS.md, "Refreshing a
source").

The only normalization is the declared scrub: every `example` and `examples` keyword value is
removed. Runpod's own examples carry an operator's SSH login (`…@ssh.runpod.io`), a pod host
address, `me@example.com` and the shape of a container-registry password, none of which this
repository has any reason to commit. `upstream_sha256` still identifies the unmodified first-party
input, so drift is measured against what Runpod actually published.
"""

from __future__ import annotations

import argparse
import copy
import datetime as dt
import hashlib
import json
import os
from pathlib import Path
import tempfile
import urllib.request

from openapi_example_scrub import operation_id_inventory, scrub_examples


SOURCE_URL = "https://api.runpod.io/v2/openapi.json"
UPSTREAM_SHA256 = "688c7b6f1d5386f04aa6d029b1c744fa11686540350e4411e8f3abe4bbf33d38"
UPSTREAM_BYTES = 214_808
UPSTREAM_VERSION = "2.0.0"
SERVER = "https://api.runpod.io"
HTTP_METHODS = {"get", "put", "post", "delete", "options", "head", "patch", "trace"}
EXPECTED_PATHS = 34
EXPECTED_OPERATIONS = 53
EXPECTED_EXAMPLE_KEYS = 313


def fail(message: str) -> None:
    raise SystemExit(message)


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def compact_json(value: object) -> bytes:
    return (json.dumps(value, sort_keys=True, separators=(",", ":")) + "\n").encode()


def provenance(fetched_at: str, scrubbed_path: str, scrubbed_sha: str, scrubbed_keys: int) -> bytes:
    rendered = f'''# Provenance for Runpod's pinned first-party REST API v2 OpenAPI document.
#
# Generated by `scripts/vendor-runpod-spec.py`; re-run the script instead of editing.
# The committed document differs from upstream only by removing every `example` and `examples`
# keyword value. `upstream_sha256` identifies the unmodified first-party input; `sha256`
# identifies the normalized bytes builds ingest.

version = 1

[[spec]]
name = "v2"
path = "{scrubbed_path}"
source_url = "{SOURCE_URL}"
openapi_version = "3.1.0"
upstream_version = "{UPSTREAM_VERSION}"
fetched_at = "{fetched_at}"
sha256 = "{scrubbed_sha}"
upstream_sha256 = "{UPSTREAM_SHA256}"
upstream_bytes = {UPSTREAM_BYTES}
paths = {EXPECTED_PATHS}
operations = {EXPECTED_OPERATIONS}

[[normalization]]
kind = "remove-example-keyword-values"
count = {scrubbed_keys}
reason = "Runpod's examples carry an SSH login, a pod host address, a placeholder email and a container-registry password field; none of them is a declaration this repository needs."
'''
    return rendered.encode()


def replace_or_check(path: Path, expected: bytes, check: bool) -> None:
    if check:
        try:
            actual = path.read_bytes()
        except FileNotFoundError:
            fail(f"missing generated file: {path}")
        if actual != expected:
            fail(f"generated file is stale: {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.tmp")
    temporary.write_bytes(expected)
    os.replace(temporary, path)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-file", type=Path)
    parser.add_argument("--fetched-at")
    parser.add_argument("--check", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if args.source_file and not args.fetched_at:
        fail("--source-file requires --fetched-at so output is reproducible")
    if args.check and not args.fetched_at:
        fail("--check requires --fetched-at from the committed provenance")
    fetched_at = args.fetched_at or dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    try:
        dt.datetime.strptime(fetched_at, "%Y-%m-%dT%H:%M:%SZ")
    except ValueError:
        fail(f"invalid --fetched-at value: {fetched_at}")

    if args.source_file:
        raw = args.source_file.read_bytes()
    else:
        with tempfile.TemporaryDirectory() as directory:
            downloaded = Path(directory) / "openapi.json"
            urllib.request.urlretrieve(SOURCE_URL, downloaded)
            raw = downloaded.read_bytes()

    if len(raw) != UPSTREAM_BYTES:
        fail(f"Runpod source byte count changed: expected {UPSTREAM_BYTES}, got {len(raw)}")
    actual_sha = sha256(raw)
    if actual_sha != UPSTREAM_SHA256:
        fail(f"Runpod source hash mismatch: expected {UPSTREAM_SHA256}, got {actual_sha}")

    document = json.loads(raw)
    if document.get("openapi") != "3.1.0":
        fail(f"Runpod source OpenAPI version changed: {document.get('openapi')!r}")
    if document.get("info", {}).get("version") != UPSTREAM_VERSION:
        fail(f"Runpod source info.version changed: {document.get('info', {}).get('version')!r}")
    servers = document.get("servers")
    if not isinstance(servers, list) or len(servers) != 1 or servers[0].get("url") != SERVER:
        fail(f"Runpod source server changed: {servers!r}")
    # The document declares one root security requirement and no per-operation override, which is
    # what lets `providers/runpod.toml` state one credential connector-wide.
    if document.get("security") != [{"bearerAuth": []}]:
        fail(f"Runpod source root security changed: {document.get('security')!r}")
    scheme = document.get("components", {}).get("securitySchemes", {}).get("bearerAuth", {})
    if scheme.get("type") != "http" or scheme.get("scheme") != "bearer":
        fail(f"Runpod's bearerAuth scheme changed: {scheme!r}")
    overridden = [
        operation.get("operationId")
        for item in document.get("paths", {}).values()
        for method, operation in item.items()
        if method in HTTP_METHODS and "security" in operation
    ]
    if overridden:
        fail(f"Runpod operations now override root security: {overridden!r}")

    paths = document.get("paths", {})
    operation_count = sum(1 for item in paths.values() for method in item if method in HTTP_METHODS)
    if len(paths) != EXPECTED_PATHS or operation_count != EXPECTED_OPERATIONS:
        fail(
            f"Runpod source inventory is {len(paths)} paths/{operation_count} operations, "
            f"expected {EXPECTED_PATHS}/{EXPECTED_OPERATIONS}"
        )
    inventory = operation_id_inventory(document)
    expected_inventory = {
        "operations": EXPECTED_OPERATIONS,
        "present": EXPECTED_OPERATIONS,
        "unique": EXPECTED_OPERATIONS,
    }
    if inventory != expected_inventory:
        fail(f"Runpod operationId inventory has a missing or duplicate id: {inventory!r}")

    scrubbed = copy.deepcopy(document)
    scrubbed_keys = scrub_examples(scrubbed)
    if scrubbed_keys != EXPECTED_EXAMPLE_KEYS:
        fail(f"Runpod example-key inventory changed: expected {EXPECTED_EXAMPLE_KEYS}, got {scrubbed_keys}")
    scrubbed_bytes = compact_json(scrubbed)

    root = Path(__file__).resolve().parent.parent
    fetched_date = fetched_at.split("T", 1)[0]
    scrubbed_rel = f"specs/runpod/openapi-{fetched_date}.json"
    generated = {
        root / scrubbed_rel: scrubbed_bytes,
        root
        / "specs/runpod.provenance.toml": provenance(
            fetched_at, scrubbed_rel, sha256(scrubbed_bytes), scrubbed_keys
        ),
    }
    for path, expected in generated.items():
        replace_or_check(path, expected, args.check)

    action = "checked" if args.check else "vendored"
    print(
        f"{action} Runpod OpenAPI v2: {len(paths)} paths/{operation_count} operations, "
        f"{scrubbed_keys} example keys scrubbed"
    )


if __name__ == "__main__":
    main()
