#!/usr/bin/env python3
"""Vendor Argo CD's published API Swagger document, and re-pin the reviewed projection beside it.

Argo CD generates `assets/swagger.json` from its protobuf service definitions and ships it in the
release tag, so the pin here is a tag plus a hash rather than a moving download: `UPSTREAM_SHA256`
is the pin, and an upstream edit fails this script loudly instead of being absorbed. Re-pinning is a
deliberate, reviewable commit (AGENTS.md, "Refreshing a source").

There is **no normalization**. Runpod and Slack need a declared scrub because their documents carry
credential-shaped examples; Argo CD's carries no `example` keyword at all, which this script asserts
rather than assumes. The committed bytes are therefore byte-identical to upstream, and `sha256` and
`upstream_sha256` are equal by construction.

The document is Swagger 2.0 and cannot be ingested directly (`crates/connector-spec/src/openapi.rs`
refuses it), so `providers/argocd.toml` reads a reviewed OpenAPI 3 projection of the exact eleven
operations B10x ships. That projection is hand-authored against these bytes, not generated
here; what this script owns is pinning it, so a projection edit that skipped a review shows up as a
provenance diff rather than passing silently.
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import os
from pathlib import Path
import tempfile
import urllib.request


UPSTREAM_TAG = "v3.5.1"
SOURCE_URL = (
    f"https://raw.githubusercontent.com/argoproj/argo-cd/{UPSTREAM_TAG}/assets/swagger.json"
)
BLOB_URL = f"https://github.com/argoproj/argo-cd/blob/{UPSTREAM_TAG}/assets/swagger.json"
UPSTREAM_SHA256 = "5cfd43dfd31446d875ab35244b19f2aaccc8120c8ddfafd90e2c25b668acaee6"
UPSTREAM_BYTES = 363_517
HTTP_METHODS = {"get", "put", "post", "delete", "options", "head", "patch", "trace"}
EXPECTED_PATHS = 82
EXPECTED_OPERATIONS = 106
EXPECTED_DEFINITIONS = 270

VENDORED_REL = f"specs/argocd/swagger-{UPSTREAM_TAG}.json"
PROJECTION_REL = f"specs/argocd/http-api-{UPSTREAM_TAG}.openapi.yaml"
PROVENANCE_REL = "specs/argocd.provenance.toml"

# Every operationId `providers/argocd.toml` selects. The projection is reviewed by hand, so the one
# mechanical guarantee worth having is that each selected id still exists upstream under the same
# path and method — a vendor rename would otherwise surface as a confusing selection failure.
SHIPPED = {
    "ApplicationService_List": ("get", "/api/v1/applications"),
    "ApplicationService_Get": ("get", "/api/v1/applications/{name}"),
    "ApplicationService_ResourceTree": (
        "get",
        "/api/v1/applications/{applicationName}/resource-tree",
    ),
    "ApplicationService_ManagedResources": (
        "get",
        "/api/v1/applications/{applicationName}/managed-resources",
    ),
    "ApplicationService_ListResourceEvents": ("get", "/api/v1/applications/{name}/events"),
    "ApplicationService_GetApplicationSyncWindows": (
        "get",
        "/api/v1/applications/{name}/syncwindows",
    ),
    "ApplicationService_Sync": ("post", "/api/v1/applications/{name}/sync"),
    "ApplicationService_Rollback": ("post", "/api/v1/applications/{name}/rollback"),
    "ApplicationService_TerminateOperation": ("delete", "/api/v1/applications/{name}/operation"),
    "ProjectService_List": ("get", "/api/v1/projects"),
    "SessionService_GetUserInfo": ("get", "/api/v1/session/userinfo"),
}

# Withheld by rule, not by omission: the platform performs authentication, so a connector never
# catalogues the endpoints that mint or destroy a session (AGENTS.md, "Adding a connector" §5).
# They are named here so that their disappearance upstream is noticed rather than silently welcomed.
AUTH_FLOW = {
    "SessionService_Create": ("post", "/api/v1/session"),
    "SessionService_Delete": ("delete", "/api/v1/session"),
}


def fail(message: str) -> None:
    raise SystemExit(message)


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def count_example_keys(value: object) -> int:
    if isinstance(value, dict):
        return sum(
            (1 if key in ("example", "examples") else 0) + count_example_keys(item)
            for key, item in value.items()
        )
    if isinstance(value, list):
        return sum(count_example_keys(item) for item in value)
    return 0


def provenance(fetched_at: str, projection_sha: str, reviewed_at: str) -> bytes:
    rendered = f'''# Provenance for Argo CD's pinned first-party API Swagger document and its reviewed projection.
#
# Generated by `scripts/vendor-argocd-spec.py`; re-run the script instead of editing.
# The vendored document is byte-identical to upstream — Argo CD's generated Swagger carries no
# `example` keyword, so there is nothing to scrub and no normalization is applied. `sha256` and
# `upstream_sha256` are therefore equal.
#
# Argo CD publishes Swagger 2.0, which this repository cannot ingest directly. The second entry is
# the reviewed OpenAPI 3 projection of the exact eleven operations `providers/argocd.toml` selects.
# It is authored and reviewed against the bytes of the first entry rather than generated from them,
# so `reviewed_at` is a claim about a person having read both, and its `sha256` is re-pinned here
# whenever the projection changes.

version = 1

[[spec]]
path = "{VENDORED_REL}"
origin = "vendor"
source_url = "{BLOB_URL}"
swagger_version = "2.0"
upstream_version = "{UPSTREAM_TAG}"
fetched_at = "{fetched_at}"
sha256 = "{UPSTREAM_SHA256}"
upstream_sha256 = "{UPSTREAM_SHA256}"
upstream_bytes = {UPSTREAM_BYTES}
paths = {EXPECTED_PATHS}
operations = {EXPECTED_OPERATIONS}
definitions = {EXPECTED_DEFINITIONS}
coverage = "complete-upstream-swagger-source"
purpose = "Pinned official Argo CD API Swagger 2 source, unmodified."

[[spec]]
path = "{PROJECTION_REL}"
origin = "vendor-derived"
derived_from = "{VENDORED_REL}"
reviewed_at = "{reviewed_at}"
sha256 = "{projection_sha}"
coverage = "exact-shipped-surface"
purpose = "OpenAPI 3 projection of the eleven Argo CD operations selected by providers/argocd.toml. Response schemas are bounded to the fields B10x promises, because the upstream Application definition is the whole custom resource. The bearer security scheme is stated from Argo CD's official API documentation, which is the one fact the Swagger source cannot corroborate: it declares no securityDefinitions at all."

[[normalization]]
kind = "none"
reason = "Argo CD's generated Swagger declares no `example` or `examples` keyword anywhere, so the committed bytes are the upstream bytes."
'''
    return rendered.encode()


def replace_or_check(path: Path, expected: bytes, check: bool) -> None:
    if check:
        try:
            actual = path.read_bytes()
        except FileNotFoundError:
            fail(f"missing generated file: {path}")
        if actual != expected:
            fail(f"generated file is stale: {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.tmp")
    temporary.write_bytes(expected)
    os.replace(temporary, path)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-file", type=Path)
    parser.add_argument("--fetched-at")
    parser.add_argument("--reviewed-at")
    parser.add_argument("--check", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if args.source_file and not args.fetched_at:
        fail("--source-file requires --fetched-at so output is reproducible")
    if args.check and not (args.fetched_at and args.reviewed_at):
        fail("--check requires --fetched-at and --reviewed-at from the committed provenance")
    now = dt.datetime.now(dt.timezone.utc)
    fetched_at = args.fetched_at or now.strftime("%Y-%m-%dT%H:%M:%SZ")
    reviewed_at = args.reviewed_at or now.strftime("%Y-%m-%d")
    try:
        dt.datetime.strptime(fetched_at, "%Y-%m-%dT%H:%M:%SZ")
        dt.datetime.strptime(reviewed_at, "%Y-%m-%d")
    except ValueError:
        fail(f"invalid timestamp: fetched_at={fetched_at!r} reviewed_at={reviewed_at!r}")

    if args.source_file:
        raw = args.source_file.read_bytes()
    else:
        with tempfile.TemporaryDirectory() as directory:
            downloaded = Path(directory) / "swagger.json"
            urllib.request.urlretrieve(SOURCE_URL, downloaded)
            raw = downloaded.read_bytes()

    if len(raw) != UPSTREAM_BYTES:
        fail(f"Argo CD source byte count changed: expected {UPSTREAM_BYTES}, got {len(raw)}")
    actual_sha = sha256(raw)
    if actual_sha != UPSTREAM_SHA256:
        fail(f"Argo CD source hash mismatch: expected {UPSTREAM_SHA256}, got {actual_sha}")

    document = json.loads(raw)
    if document.get("swagger") != "2.0":
        fail(f"Argo CD source is no longer Swagger 2.0: {document.get('swagger')!r}")
    # Asserted rather than assumed: the moment Argo CD starts publishing examples, this connector
    # owes a declared scrub and this script must stop claiming there is nothing to remove.
    example_keys = count_example_keys(document)
    if example_keys != 0:
        fail(
            f"Argo CD source now carries {example_keys} example keyword(s); this connector's "
            "no-normalization claim no longer holds and needs a declared scrub"
        )
    # Argo CD's generated document declares no security vocabulary at all. `providers/argocd.toml`
    # states the bearer requirement from Argo CD's documentation instead, and that stays honest only
    # while the source really is silent — a later securityDefinitions block would be the authority.
    if document.get("securityDefinitions") is not None or document.get("security") is not None:
        fail(
            "Argo CD source now declares security; the reviewed projection states the bearer "
            "scheme from documentation and must be re-derived from the source instead"
        )

    paths = document.get("paths", {})
    operation_count = sum(1 for item in paths.values() for method in item if method in HTTP_METHODS)
    definitions = document.get("definitions", {})
    if (
        len(paths) != EXPECTED_PATHS
        or operation_count != EXPECTED_OPERATIONS
        or len(definitions) != EXPECTED_DEFINITIONS
    ):
        fail(
            f"Argo CD source inventory is {len(paths)} paths/{operation_count} operations/"
            f"{len(definitions)} definitions, expected {EXPECTED_PATHS}/{EXPECTED_OPERATIONS}/"
            f"{EXPECTED_DEFINITIONS}"
        )

    located = {
        operation.get("operationId"): (method, path)
        for path, item in paths.items()
        for method, operation in item.items()
        if method in HTTP_METHODS
    }
    for operation_id, expected in SHIPPED.items():
        if located.get(operation_id) != expected:
            fail(
                f"shipped operation {operation_id!r} is {located.get(operation_id)!r} upstream, "
                f"expected {expected!r}"
            )
    for operation_id, expected in AUTH_FLOW.items():
        if located.get(operation_id) != expected:
            fail(
                f"withheld auth-flow operation {operation_id!r} is {located.get(operation_id)!r} "
                f"upstream, expected {expected!r}; re-review what this connector withholds"
            )

    root = Path(__file__).resolve().parent.parent
    projection = root / PROJECTION_REL
    if not projection.is_file():
        fail(f"missing reviewed projection: {PROJECTION_REL}")
    projection_sha = sha256(projection.read_bytes())

    generated = {
        root / VENDORED_REL: raw,
        root / PROVENANCE_REL: provenance(fetched_at, projection_sha, reviewed_at),
    }
    for path, expected in generated.items():
        replace_or_check(path, expected, args.check)

    action = "checked" if args.check else "vendored"
    print(
        f"{action} Argo CD API Swagger {UPSTREAM_TAG}: {len(paths)} paths/{operation_count} "
        f"operations/{len(definitions)} definitions, 0 example keys, "
        f"{len(SHIPPED)} shipped operations located"
    )


if __name__ == "__main__":
    main()
