import React,{useEffect,useRef,useState} from 'react';
import Link from '@docusaurus/Link';
import useBaseUrl from '@docusaurus/useBaseUrl';
import {openLab} from './lab-bridge';
import type {Snapshot} from './lab-bridge';

type Scenario='discovery'|'readiness'|'mutation';
const scenarios:Record<Scenario,{title:string;intro:string;steps:string[];actions:[string,string][];rules:[string,string][]}>={
  discovery:{title:'Discovery does not grant access',intro:'A Kubernetes observation tells you where a database might be. Follow the explicit steps that make an SQL read eligible.',steps:['discover','read','bind','read','change_target','bind','withdraw','read'],actions:[['discover','Discover endpoint'],['bind','Configure connection'],['read','Try a read'],['change_target','Change candidate'],['withdraw','Withdraw observation'],['advance_time','Advance clock'],['revalidate','Validate current binding']],rules:[['/contracts/discovery/resources','Resource discovery'],['/contracts/auth/connection#41-connection-viability-and-operation-eligibility','Connection eligibility'],['/contracts/discovery/composition','Composition']]},
  readiness:{title:'Ready for which operation?',intro:'Global readiness and permission for a particular request answer different questions. Change the fictional environment and try the read.',steps:['read','toggle_permission','read','toggle_permission','advance_time','read','revalidate','read','revoke'],actions:[['read','Try a read'],['toggle_permission','Toggle permission'],['toggle_scope','Toggle operation scope'],['toggle_custody','Toggle custody'],['toggle_credential','Toggle credential validity'],['toggle_admission','Toggle host admission'],['advance_time','Advance clock'],['revalidate','Validate current binding'],['revoke','Revoke connection']],rules:[['/contracts/auth/connection#41-connection-viability-and-operation-eligibility','Readiness reduction'],['/contracts/auth/evidence','Evidence freshness']]},
  mutation:{title:'The response disappeared',intro:'Prepare a mutation, dispatch it once, then lose the response. The example preserves uncertainty and refuses another send.',steps:['prepare','approve','prepare','dispatch','lose_response','retry','dispatch','complete'],actions:[['approve','Supply approval'],['prepare','Prepare attempt'],['dispatch','Dispatch once'],['lose_response','Lose response'],['complete','Record success'],['retry','Retry same request'],['conflicting_input','Try conflicting input'],['abort','Abort before dispatch'],['toggle_admission','Toggle host admission'],['advance_time','Advance clock']],rules:[['/contracts/mutations','Mutation and idempotency'],['/contracts/model/domains/connectors-mutations','Generated lifecycle']]},
};
function StateCard({label,value,good}:{label:string;value:string;good?:boolean}){return <div className={'lab-state'+(good===true?' good':good===false?' blocked':'')}><span>{label}</span><strong>{value.replaceAll('_',' ')}</strong></div>;}
export default function ContractLab({initial='discovery'}:{initial?:Scenario}){
  const [scenario,setScenario]=useState<Scenario>(initial);const [snapshot,setSnapshot]=useState<Snapshot>();const [error,setError]=useState('');const [step,setStep]=useState(0);
  const driver=useRef<Awaited<ReturnType<typeof openLab>> | undefined>(undefined);const wasm=useBaseUrl('/examples/contracts.wasm');
  useEffect(()=>{let active=true;fetch(wasm).then(response=>{if(!response.ok)throw new Error('The example module could not be loaded. Run npm run examples, then reload.');return response.arrayBuffer();}).then(openLab).then(open=>{if(active){driver.current=open;setSnapshot(open({scenario:initial}));}}).catch(reason=>{if(active)setError(String(reason));});return ()=>{active=false;};},[wasm,initial]);
  const selected=scenarios[scenario];
  function act(action:string){try{if(driver.current)setSnapshot(driver.current({action}));}catch(reason){setError(String(reason));}}
  function select(next:Scenario){if(!driver.current)return;setScenario(next);setStep(0);setError('');try{setSnapshot(driver.current({scenario:next}));}catch(reason){setError(String(reason));}}
  return <div className="contract-lab">
    <div className="lab-tabs" role="group" aria-label="Choose an example">{(Object.keys(scenarios) as Scenario[]).map(key=><button type="button" key={key} aria-pressed={key===scenario} className={key===scenario?'selected':''} onClick={()=>select(key)}>{key==='discovery'?'01 · Discovery':key==='readiness'?'02 · Readiness':'03 · Uncertain outcomes'}</button>)}</div>
    <div className="lab-heading"><span className="eyebrow">EXECUTABLE EXAMPLE · RUST / WEBASSEMBLY</span><h2>{selected.title}</h2><p>{selected.intro}</p></div>
    <p className="lab-boundary">In-memory behavior, fictional data, deterministic time. This demonstrates selected contract rules; it does not establish production durability, cryptographic verification or provider conformance.</p>
    {error?<div className="alert alert--danger" role="alert">{error}</div>:!snapshot?<p role="status">Loading the example engine…</p>:<>
      <div className="lab-toolbar" data-pagefind-ignore><button className="button button--primary" onClick={()=>{if(step<selected.steps.length){act(selected.steps[step]);setStep(step+1);}}} disabled={step>=selected.steps.length}>Next guided step <span aria-hidden="true">→</span></button><span>{step} / {selected.steps.length}</span><button className="lab-reset" onClick={()=>{act('reset');setStep(0);}}>Reset example</button><span className="lab-clock">Example clock: +{snapshot.clock}s</span></div>
      <div className="lab-workspace"><div className="lab-controls" data-pagefind-ignore><h3>Try a different path</h3><p>These controls inject example facts or run an admitted scenario action.</p>{selected.actions.map(([action,label])=><button key={action} type="button" onClick={()=>act(action)}>{label}<span aria-hidden="true">↗</span></button>)}</div>
      <div className="lab-observation">
        {scenario==='mutation'?<><div className="lab-state-grid"><StateCard label="ATTEMPT STATE" value={snapshot.attempt}/><StateCard label="PROVIDER SENDS" value={String(snapshot.provider_sends)}/><StateCard label="APPROVAL REDEMPTIONS" value={String(snapshot.approval_redemptions)}/></div><div className="lifecycle-track" aria-label="Mutation lifecycle">{['Prepared','Dispatching','Indeterminate'].map((state,i)=><React.Fragment key={state}>{i>0&&<span aria-hidden="true">→</span>}<div className={snapshot.attempt===state?'current':''}>{state}</div></React.Fragment>)}</div><p className="lab-explanation">Success, known refusal and abort have their own terminal paths. An indeterminate attempt cannot return to dispatching.</p></>:<><div className="lab-state-grid"><StateCard label="OBSERVATION" value={snapshot.observation}/><StateCard label="CONNECTION" value={snapshot.connection}/></div><div className="lab-binding"><div><span>Discovered candidate</span><code>{snapshot.candidate}</code></div><div><span>Fixed connection target</span><code>{snapshot.target??'No binding selected'}</code></div></div></>}
        <div className="lab-state-grid"><StateCard label="GLOBAL VIABILITY" value={snapshot.viability} good={snapshot.viability==='ready'}/><StateCard label="OPERATION ELIGIBILITY" value={snapshot.eligibility} good={snapshot.eligibility==='eligible'}/></div>
        <div className="lab-facts"><span>Host admission: <b>{snapshot.admitted?'allowed':'denied'}</b></span><span>Permission: <b>{snapshot.permission}</b></span><span>Operation scope: <b>{snapshot.scope}</b></span><span>Custody: <b>{snapshot.custody?'available':'unavailable'}</b></span></div>
      </div></div>
      <div className="lab-timeline"><h3>What happened</h3><div role="log" aria-label="Command and outcome timeline" aria-live="polite">{snapshot.timeline.length===0?<p className="lab-empty">Run a guided step or choose an action. Results come from the WASM engine.</p>:[...snapshot.timeline].reverse().map((entry,i)=><div className="lab-event" key={snapshot.timeline.length-i}><span className="lab-event-index">{String(snapshot.timeline.length-i).padStart(2,'0')}</span><div><strong>{entry.action.replaceAll('_',' ')} <span aria-hidden="true">→</span> <code>{entry.outcome}</code></strong><p>{entry.explanation}</p></div></div>)}</div></div>
      <details className="lab-technical"><summary>What this example actually executes</summary><p>Mutation commands use ESS-generated Rust ports and typestate transitions over the canonical model. The other exercises evaluate authored Rust predicates over fictional discovery and access facts using generated types. Scenario actions compose those behaviors; they are not new public service commands. The namespace, principal, provider identity and request choices are fixed for this bounded exercise.</p><p>The approval receipt and idempotency lookup are in-memory example bindings. Distributed atomicity, cryptographic claims, retention cleanup and audit persistence are outside this module. No credential or external network call is involved.</p><details><summary>Events from generated mutation ports</summary><pre>{snapshot.events.length?snapshot.events.join('\n'):'No mutation events published.'}</pre></details></details>
    </>}
    <div className="lab-rules"><strong>Read the rules</strong>{selected.rules.map(([to,label])=><Link to={to} key={to}>{label} ↗</Link>)}</div>
  </div>;
}
