import React,{useEffect,useId,useRef,useState} from 'react';
import Link from '@docusaurus/Link';
import useBaseUrl from '@docusaurus/useBaseUrl';
import {openExampleEngine} from './lab-bridge';

type Mode='configured'|'governed';
type NodeId='client'|'gateway'|'adapter'|'provider'|'identity'|'custody';
type Frame={id:string;title:string;explanation:string;from:NodeId;to:NodeId;message:string;credential:string;phase:string;rule:string;payload:unknown;error:string|null};
type Issue={iid:number;title:string;state:string};
type Snapshot={mode:Mode;situation:string;index:number;total:number;done:boolean;waiting_for_read:boolean;step:Frame|null;result:{items:Issue[];complete:boolean;next_cursor:string|null;provenance:{instance:string;resource:string}}|null;provider_calls:number;visited:string[];error?:string};
type Request={mode?:Mode;situation?:string;action?:'next'|'back'|'restart'|'read'};
const modes:Record<Mode,{label:string;status:string;cases:[string,string][]}>={
  configured:{label:'Configured access',status:'This federation behavior is available today',cases:[['success','The request succeeds'],['gateway_denied','Gateway access is denied'],['adapter_unreachable','The adapter is unreachable'],['provider_rejected','GitLab rejects its credential']]},
  governed:{label:'User authorization',status:'Specified architecture · runtime implementation pending',cases:[['success','Connect GitLab, then read issues'],['consent_declined','You decline GitLab consent'],['connection_denied','Connection access is denied'],['custody_unavailable','Credential custody is unavailable']]},
};
const names:Record<NodeId,string>={client:'Your application',gateway:'Federation gateway',adapter:'GitLab adapter',provider:'GitLab',identity:'Identity service',custody:'Credential custody'};
const credentials:Record<string,{title:string;description:string;owner:string}>={
  none:{title:'Request or safe result data',description:'This arrow carries operation information, business input, a result or a safe failure. It does not carry a provider credential.',owner:'Credential values are not part of operation input or results.'},
  client_service:{title:'Client → gateway credential',description:'Authenticates access to the gateway. A shared service credential identifies configured access, not each individual person using it.',owner:'Configured for your client and verified by the gateway.'},
  downstream_service:{title:'Gateway → adapter credential',description:'A separate service credential authenticates the gateway to this adapter. It is not the credential supplied by the client.',owner:'Configured on the gateway; verified by the adapter service.'},
  provider:{title:'Adapter → GitLab credential',description:'Used only inside the selected provider execution or authorization boundary. It does not pass through the federation gateway or reach your application.',owner:'Owned by the executing adapter’s auth and custody bindings.'},
  identity:{title:'Your application identity',description:'The identity service authenticates you. Connectors accepts access issued for its configured audience and still checks current policy.',owner:'Presented by the application; verified at Connectors admission.'},
  delegation:{title:'Scoped, signed delegation',description:'The gateway binds verified caller authority to this receiving service and request. The receiver verifies it and independently decides whether access is allowed.',owner:'Signed by the gateway; verified by the receiving host.'},
  consent:{title:'Provider consent in a trusted browser flow',description:'You authorize provider access at GitLab. Being logged in to the application does not grant that access.',owner:'A separately admitted trusted UI handles the browser continuation.'},
  callback:{title:'Protected callback evidence',description:'The coordinator verifies the callback’s correlation and one-time use. This is not an ordinary business invocation or a reusable URL returned to the caller.',owner:'Received at the owning coordinator’s trusted callback binding.'},
  exchange:{title:'Server-side authorization exchange',description:'The adapter’s provider auth implementation exchanges validated evidence. Its exact OAuth parameters must come from an authored provider profile.',owner:'Occurs between the owning adapter service and GitLab.'},
  connection:{title:'A safe connection reference',description:'The application can select this reference for a later admitted request. The reference is not a token and does not itself grant access.',owner:'Safe metadata can travel back through the gateway.'},
};

function Icon({kind}:{kind:'laptop'|'server'|'cloud'|'key'|'lock'}){
  return <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{kind==='laptop'?<><rect x="4" y="3" width="16" height="12" rx="2"/><path d="M2 19h20l-2-4H4z"/></>:kind==='server'?<><rect x="4" y="2" width="16" height="8" rx="2"/><rect x="4" y="14" width="16" height="8" rx="2"/><path d="M8 6h.01M8 18h.01M12 6h4M12 18h4"/></>:kind==='cloud'?<path d="M6 18a5 5 0 0 1-1-10 7 7 0 0 1 13-1 5.5 5.5 0 0 1 0 11Z"/>:kind==='key'?<><circle cx="8" cy="8" r="5"/><path d="m12 12 9 9m-4-4 3-3m-6 0 3-3"/></>:<><rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3m-4 5v2"/></>}</svg>;
}

function DeploymentDiagram({mode,step,playing=false}:{mode:Mode;step:Frame|null;playing?:boolean}){
  const container=useRef<HTMLDivElement>(null);
  const nodes=useRef<Partial<Record<NodeId,HTMLDivElement|null>>>({});
  const [geometry,setGeometry]=useState<{width:number;height:number;paths:Record<string,string>}>({width:1,height:1,paths:{}});
  const marker=useId().replaceAll(':','');
  useEffect(()=>{
    const parent=container.current;if(!parent)return;
    function measure(){
      const root=parent!.getBoundingClientRect();const paths:Record<string,string>={};
      const pairs:[NodeId,NodeId][]=[['client','gateway'],['gateway','adapter'],['adapter','provider'],['client','identity'],['adapter','custody']];
      if(step&&step.from!==step.to)pairs.push([step.from,step.to]);
      for(const [from,to] of pairs){
        const a=nodes.current[from]?.getBoundingClientRect(),b=nodes.current[to]?.getBoundingClientRect();if(!a||!b)continue;
        let x1=a.x+a.width/2-root.x,y1=a.y+a.height/2-root.y,x2=b.x+b.width/2-root.x,y2=b.y+b.height/2-root.y;
        const skipsNode=Math.abs(x2-x1)<40&&Object.entries(nodes.current).some(([id,node])=>{if(!node||id===from||id===to)return false;const box=node.getBoundingClientRect(),cx=box.x+box.width/2-root.x,cy=box.y+box.height/2-root.y;return Math.abs(cx-x1)<40&&cy>Math.min(y1,y2)&&cy<Math.max(y1,y2);});
        if(skipsNode){const lane=root.width-7;paths[from+'-'+to]=`M ${a.right-root.x} ${y1} H ${lane} V ${y2} H ${b.right-root.x}`;}
        else if((from==='client'&&to==='provider')||(from==='provider'&&to==='client')){y1=a.top-root.y;y2=b.top-root.y;const lane=Math.min(y1,y2)-55;paths[from+'-'+to]=`M ${x1} ${y1} C ${x1} ${lane}, ${x2} ${lane}, ${x2} ${y2}`;}
        else if(Math.abs(x2-x1)>Math.abs(y2-y1)){const dir=Math.sign(x2-x1);x1+=dir*a.width/2;x2-=dir*b.width/2;const bend=(x2-x1)/2;paths[from+'-'+to]=`M ${x1} ${y1} C ${x1+bend} ${y1}, ${x2-bend} ${y2}, ${x2} ${y2}`;}
        else{const dir=Math.sign(y2-y1);y1+=dir*a.height/2;y2-=dir*b.height/2;const bend=(y2-y1)/2;paths[from+'-'+to]=`M ${x1} ${y1} C ${x1} ${y1+bend}, ${x2} ${y2-bend}, ${x2} ${y2}`;}
      }
      setGeometry({width:root.width,height:root.height,paths});
    }
    const observer=new ResizeObserver(measure);observer.observe(parent);Object.values(nodes.current).forEach(node=>{if(node)observer.observe(node);});measure();return ()=>observer.disconnect();
  },[mode,step?.from,step?.to]);
  function node(id:NodeId,detail:string,credential?:string){const active=step&&(step.from===id||step.to===id);return <div ref={element=>{nodes.current[id]=element;}} data-node={id} className={'journey-node'+(active?' is-active':'')+(active&&step.error?' is-refused':'')}><Icon kind={id==='client'?'laptop':id==='provider'?'cloud':id==='custody'?'lock':id==='identity'?'key':'server'}/><strong>{names[id]}</strong><span>{detail}</span>{credential&&<small><Icon kind="key"/>{credential}</small>}{active&&step.from===step.to&&<b className="node-check">{step.error?'Request stopped':'Checking here'}</b>}</div>;}
  const active=step?geometry.paths[step.from+'-'+step.to]:null;
  return <div className="journey-diagram" ref={container} aria-label="Request route from your laptop through remote Connectors services to GitLab">
    <div className="journey-client-column"><div className="deployment-zone laptop-zone"><div className="zone-heading">01 <strong>Your laptop</strong></div>{node('client','CLI, app or agent',mode==='configured'?'Gateway access':'Your application identity')}</div>{mode==='governed'&&<div className="deployment-zone identity-zone"><div className="zone-heading"><strong>Separate identity service</strong></div>{node('identity','Authenticates the application user')}</div>}</div>
    <div className="deployment-zone remote-zone"><div className="zone-heading">02 <strong>Remote Connectors host</strong></div>{node('gateway','Routes the operation',mode==='configured'?'Adapter service access':'Delegation signing key')}{node('adapter','Knows the GitLab API','GitLab access')}{mode==='governed'&&node('custody','Private host capability')}<p className="placement-note">Two services shown together; they can be deployed separately.</p></div>
    <div className="deployment-zone provider-zone"><div className="zone-heading">03 <strong>Third-party service</strong></div>{node('provider','acme/website · project issues')}<div className="provider-preview"><span>YOUR REQUEST</span><strong>Project issues</strong><span>At most 20 records</span></div></div>
    <svg className="journey-wires" viewBox={`0 0 ${geometry.width} ${geometry.height}`} width={geometry.width} height={geometry.height} aria-hidden="true"><defs><marker id={marker} viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="currentColor"/></marker></defs>{['client-gateway','gateway-adapter','adapter-provider'].map(id=>geometry.paths[id]&&<path key={id} d={geometry.paths[id]} className="wire-base"/>)}{active&&<path key={step!.id} d={active} className={'wire-active'+(step?.error?' wire-error':'')} style={{animationPlayState:playing?'running':'paused'}} markerEnd={`url(#${marker})`}/>}</svg>
  </div>;
}

export default function RequestWalkthrough(){
  const [snapshot,setSnapshot]=useState<Snapshot>();const [error,setError]=useState('');const [playing,setPlaying]=useState(false);
  const driver=useRef<((request:Request)=>Snapshot)|undefined>(undefined);const wasm=useBaseUrl('/examples/contracts.wasm');
  useEffect(()=>{let active=true;fetch(wasm).then(response=>{if(!response.ok)throw new Error('The walkthrough could not be loaded. Reload this page to try again.');return response.arrayBuffer();}).then(bytes=>openExampleEngine<Request,Snapshot>(bytes,'walkthrough_dispatch')).then(open=>{if(active){driver.current=open;setSnapshot(open({}));}}).catch(reason=>{if(active)setError(String(reason));});return ()=>{active=false;};},[wasm]);
  function send(request:Request){if(!driver.current)return;try{const next=driver.current(request);setSnapshot(next);if(next.done||next.waiting_for_read)setPlaying(false);}catch(reason){setPlaying(false);setError(String(reason));}}
  useEffect(()=>{if(!playing||!snapshot||snapshot.done||snapshot.waiting_for_read)return;const timer=window.setTimeout(()=>send({action:'next'}),6000);return ()=>window.clearTimeout(timer);},[playing,snapshot]);
  const mode=snapshot?.mode??'configured',step=snapshot?.step,credential=credentials[step?.credential??'none'];
  function select(request:Request){setPlaying(false);send(request);}
  return <section className="request-journey" aria-label="GitLab request walkthrough">
    <div className="journey-tabs" role="group" aria-label="Choose a walkthrough">{(['configured','governed'] as Mode[]).map(value=><button key={value} disabled={!snapshot||!!error} aria-pressed={mode===value} onClick={()=>select({mode:value})}>{modes[value].label}<span>{value==='configured'?'Available today':'Specified architecture'}</span></button>)}</div>
    <div className="journey-context"><span className={'journey-status '+mode}>{modes[mode].status}</span><label>Explore a situation<select aria-label="Explore a situation" value={snapshot?.situation??'success'} disabled={!snapshot||!!error} onChange={event=>select({situation:event.target.value})}>{modes[mode].cases.map(([value,title])=><option key={value} value={value}>{title}</option>)}</select></label></div>
    {mode==='governed'&&<div className="journey-phases"><span className={step?.phase==='identity'?'current':''}>1. Sign in</span><span aria-hidden="true">→</span><span className={step?.phase==='connect'?'current':''}>2. Connect GitLab</span><span aria-hidden="true">→</span><span className={step?.phase==='read'?'current':''}>3. Read issues</span></div>}
    {(!snapshot||error)&&<DeploymentDiagram mode={mode} step={step??null}/>}
    {error?<div className="alert alert--danger journey-load-error" role="alert">{error} The explanation above is still available; no request has been executed.</div>:!snapshot?<p className="journey-loading" role="status">Loading the walkthrough…</p>:<>
      <div className="journey-toolbar" data-pagefind-ignore><div className="journey-playback"><button className="button button--primary" disabled={snapshot.done||snapshot.waiting_for_read} onClick={()=>{if(playing){setPlaying(false);}else{setPlaying(true);send({action:'next'});}}}>{playing?'Pause':'Play'}</button><button disabled={snapshot.index===0} onClick={()=>select({action:'back'})}>Back</button>{snapshot.waiting_for_read?<button className="button button--primary" onClick={()=>select({action:'read'})}>Read issues</button>:<button disabled={snapshot.done} onClick={()=>select({action:'next'})}>Next <span aria-hidden="true">→</span></button>}<button onClick={()=>select({action:'restart'})}>Restart</button></div><span className="journey-progress">{snapshot.index===0?'Ready to start':`Step ${snapshot.index} of ${snapshot.total}`}</span><progress max={snapshot.total} value={snapshot.index} aria-label="Walkthrough progress"/></div>
      <div className="journey-stage"><DeploymentDiagram mode={mode} step={step??null} playing={playing}/>
      <div className="journey-narration" aria-live="polite" aria-atomic="true"><div className="journey-explanation"><span className="eyebrow">{step?`${names[step.from]}${step.from!==step.to?' → '+names[step.to]:''}`:'A REQUEST YOU CAN FOLLOW'}</span><h2>{step?.title??(mode==='configured'?'Your application needs some project issues.':'Two kinds of sign-in. One deliberate request.')}</h2><p>{step?.explanation??(mode==='configured'?'The remote host already has a route to a GitLab adapter. Follow how your request reaches the project, which credentials are checked, and how the answer comes back.':'First establish application identity and authorize provider access. Then make a separate issue request under the receiving host’s current policy. These are specified flows, illustrated with fictional data.')}</p>{step&&<div className={'journey-message'+(step.error?' is-error':'')}><span>{step.error?'STOPPED':'ON THIS STEP'}</span><strong>{step.message}</strong></div>}{snapshot.waiting_for_read&&<p className="journey-pause-note">Playback pauses here. Choose <strong>Read issues</strong> to start the business request.</p>}</div><aside className="journey-credential"><Icon kind={step?.credential==='none'||!step?'lock':'key'}/><h3>{step?credential.title:'Three separate access boundaries'}</h3><p>{step?credential.description:'Access to the gateway, access to the adapter service and access to GitLab are separate checks. The request does not carry one universal credential.'}</p><div>{step?credential.owner:'The diagram shows where each credential is held and where it is used.'}</div></aside></div>
      </div>
      {snapshot.result&&<div className="journey-result" role="region" aria-label="Returned GitLab issues"><div><span className="eyebrow">BACK IN YOUR APPLICATION</span><h2>Issues in acme/website</h2><p>3 issues returned · no further page in this example</p></div><table><thead><tr><th>Issue</th><th>Title</th><th>State</th></tr></thead><tbody>{snapshot.result.items.map(issue=><tr key={issue.iid}><td>#{issue.iid}</td><td>{issue.title}</td><td><span className={'issue-state '+issue.state}>{issue.state==='opened'?'Open':'Closed'}</span></td></tr>)}</tbody></table><p className="result-provenance">Source: {snapshot.result.provenance.instance} · {snapshot.result.provenance.resource}</p></div>}
      <details className="journey-details" data-pagefind-ignore><summary>Request details and contract rules</summary><p>This is an illustrated journey with fictional data. Rust/WASM supplies its deterministic steps; it does not run a service, verify credentials, perform OAuth or call GitLab. GitLab issue requests illustrated so far: <strong>{snapshot.provider_calls}</strong>.</p>{step?.error&&<p>Safe outcome: <code>{step.error}</code>{snapshot.mode==='governed'&&snapshot.situation==='consent_declined'?' is an acquisition failure reason, not a new service error code.':''}</p>}{step?.payload!=null&&<pre><code>{JSON.stringify(step.payload,null,2)}</code></pre>}<Link to={step?.rule??'/contracts/service'}>Read the owning contract →</Link>{mode==='governed'&&<p>Identity issuance, trusted UI, custody, cryptography and durable verification are specified binding responsibilities. Provider-specific OAuth endpoints and parameters are intentionally not invented here.</p>}</details>
    </>}
    <details className="journey-prerequisites"><summary>{mode==='configured'?'What is configured before this call?':'Where do these services live?'}</summary><p>{mode==='configured'?'An operator configures the gateway route and downstream service credential, the adapter’s permitted project and GitLab origin, and the provider credential. The client has a separate gateway credential. The gateway has already loaded the downstream description; a caller’s describe request does not create a route.':'The diagram groups the gateway and adapter services in one remote deployment for readability. They may run separately. The identity service is a distinct authentication boundary, and the coordinator and custody are capabilities bound by the executing host.'}</p><p>Remote service traffic needs the intended verified TLS boundaries. The walkthrough uses no real credentials and makes no provider requests.</p></details>
  </section>;
}
