import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';
import path from 'node:path';
import type {LoadContext, Plugin, PluginConfig, RouteConfig} from '@docusaurus/types';
import {withProductSite} from '@beyond10x/docs-system/product-site';

// Pages under docs/reference/contracts/, docs/reference/adapters/*/contracts/ and
// docs/reference/adapters/*/model/, docs/reference/cli.md, docs/reference/crates.md,
// docs/status.md and data/status.json are generated by `connectors-docs generate`;
// everything else under docs/ is written by hand.
const config: Config = {
  title: 'Connectors',
  tagline: 'Independent integrations. Shared guarantees.',
  favicon: 'img/mark.svg',

  url: 'https://beyond10x.github.io',
  baseUrl: '/connectors/',

  organizationName: 'beyond10x',
  projectName: 'connectors',
  deploymentBranch: 'gh-pages',
  trailingSlash: false,

  onBrokenLinks: 'throw',
  onBrokenAnchors: 'throw',

  markdown: {
    format: 'detect',
    mermaid: true,
    hooks: {
      onBrokenMarkdownLinks: 'throw',
    },
  },

  themes: ['@docusaurus/theme-mermaid'],
  plugins: ['./plugins/audit.ts'],

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  presets: [
    [
      'classic',
      {
        docs: {
          path: 'docs',
          routeBasePath: 'docs',
          sidebarPath: './sidebars.ts',
          editUrl: 'https://github.com/beyond10x/connectors/tree/main/website/',
        },
        blog: false,
        theme: {customCss: ['./src/css/examples.css', './src/css/tables.css']},
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    navbar: {
      title: 'Connectors',
      logo: {
        alt: 'Connectors mark',
        src: 'img/mark.svg',
      },
      items: [
        {to: '/docs/', label: 'Documentation', position: 'left'},
        {to: '/docs/getting-started', label: 'Get started', position: 'left'},
        {to: '/docs/reference/contracts', label: 'Contracts', position: 'left'},
        {to: '/docs/reference/adapters', label: 'Adapters', position: 'left'},
        {to: '/docs/status', label: 'Status', position: 'left'},
        {href: 'https://github.com/beyond10x/connectors', label: 'GitHub', position: 'right'},
      ],
    },
    footer: {
      links: [
        {
          title: 'Documentation',
          items: [
            {label: 'Overview', to: '/docs/'},
            {label: 'Getting started', to: '/docs/getting-started'},
            {label: 'Contracts and guarantees', to: '/docs/concepts/contracts'},
            {label: 'Federate adapter services', to: '/docs/guides/federate-adapter-services'},
            {label: 'Follow a request', to: '/docs/examples/follow-a-request'},
            {label: 'connectors CLI', to: '/docs/reference/cli'},
            {label: 'Contract reference', to: '/docs/reference/contracts'},
            {label: 'Status', to: '/docs/status'},
          ],
        },
        {
          title: 'Project',
          items: [
            {label: 'Source', href: 'https://github.com/beyond10x/connectors'},
            {label: 'Releases', href: 'https://github.com/beyond10x/connectors/releases'},
            {label: 'Changelog', href: 'https://github.com/beyond10x/connectors/blob/main/CHANGELOG.md'},
          ],
        },
      ],
      copyright: 'A beyond10x project. Connectors · MIT OR Apache-2.0.',
    },
  } satisfies Preset.ThemeConfig,
};

// The product layer hands Docusaurus two absolute build paths, the font directory and the landing
// data module, and Docusaurus serializes both into the client bundle, where the public-output
// audit refuses them. Name them relative to the site and through the '@generated' alias instead.
type PluginFactory = (context: LoadContext, options: unknown) => Plugin;

function portable(site: Config): Config {
  const relative = (directory: string | undefined) =>
    directory && path.isAbsolute(directory)
      ? path.relative(__dirname, directory).split(path.sep).join('/')
      : directory;
  const aliased = (factory: PluginFactory): PluginFactory =>
    function portableModules(context, options) {
      const plugin = factory(context, options);
      const contentLoaded = plugin.contentLoaded?.bind(plugin);
      if (!contentLoaded) return plugin;
      const alias = (module: unknown) =>
        typeof module === 'string' && module.startsWith(context.generatedFilesDir)
          ? '@generated/' + path.relative(context.generatedFilesDir, module).split(path.sep).join('/')
          : module;
      return {
        ...plugin,
        contentLoaded: ({content, actions}) =>
          contentLoaded({
            content,
            actions: {
              ...actions,
              addRoute: (route: RouteConfig) =>
                actions.addRoute({
                  ...route,
                  modules: Object.fromEntries(
                    Object.entries(route.modules ?? {}).map(([name, module]) => [name, alias(module)]),
                  ) as RouteConfig['modules'],
                }),
            },
          }),
      };
    };
  const plugins = (site.plugins ?? []) as unknown[];
  return {
    ...site,
    staticDirectories: (site.staticDirectories ?? ['static']).map(relative) as string[],
    plugins: plugins.map((entry) =>
      Array.isArray(entry) && typeof entry[0] === 'function'
        ? [aliased(entry[0] as PluginFactory), entry[1]]
        : entry,
    ) as PluginConfig[],
  };
}

export default portable(withProductSite(config, {landing: './product.json', mark: 'C'}));
