import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
const sidebars: SidebarsConfig = {
  introduction: [{type: 'autogenerated', dirName: 'introduction'}],
  contracts: [{type: 'autogenerated', dirName: 'contracts'}],
  adapters: [{type: 'autogenerated', dirName: 'adapters'}],
};
export default sidebars;
