//! The crate list, from `cargo metadata --no-deps`: every workspace package, its directory, the
//! name Rust code uses for it, and its `description`.

use std::{path::Path, process::Command};

use serde_json::Value;

use crate::{Result, cell, front_matter};

/// Where the crate list lands, relative to the repository root.
pub const PAGE: &str = "website/docs/reference/crates.md";
/// A directory in the repository on GitHub, by path.
const TREE: &str = "https://github.com/beyond10x/connectors/tree/main";

/// One workspace package as the page lists it.
#[derive(Debug, PartialEq, Eq)]
struct Package {
    name: String,
    directory: String,
    /// The library name (`use <lib>`), when the package has a library.
    lib: Option<String>,
    /// The binaries it builds.
    bins: Vec<String>,
    description: String,
}

/// Which table a package belongs on.
#[derive(Clone, Copy, PartialEq, Eq)]
enum Group {
    Adapter,
    Application,
    Tooling,
}

fn group(package: &Package) -> Group {
    if package.directory.starts_with("adapters/") {
        Group::Adapter
    } else if [
        "connectors-build",
        "connectors-docs",
        "connectors-conformance",
    ]
    .contains(&package.name.as_str())
    {
        Group::Tooling
    } else {
        Group::Application
    }
}

/// The packages of a `cargo metadata --format-version 1` document, sorted by name, with their
/// directories relative to `workspace_root`. A package without a description is refused: the
/// page would have nothing to say about it.
fn packages(metadata: &Value) -> Result<Vec<Package>> {
    let root = metadata["workspace_root"]
        .as_str()
        .ok_or("cargo metadata names no workspace_root")?;
    let mut found = Vec::new();
    for package in metadata["packages"]
        .as_array()
        .ok_or("cargo metadata lists no packages")?
    {
        let name = package["name"]
            .as_str()
            .ok_or("a package has no name")?
            .to_owned();
        let manifest = package["manifest_path"]
            .as_str()
            .ok_or_else(|| format!("{name} has no manifest_path"))?;
        let directory = Path::new(manifest)
            .parent()
            .and_then(|dir| dir.strip_prefix(root).ok())
            .ok_or_else(|| format!("{name} lies outside the workspace"))?
            .to_string_lossy()
            .into_owned();
        let Some(description) = package["description"].as_str() else {
            return Err(format!("{name} has no description in its Cargo.toml"));
        };
        let mut lib = None;
        let mut bins = Vec::new();
        for target in package["targets"].as_array().into_iter().flatten() {
            let kinds: Vec<&str> = target["kind"]
                .as_array()
                .into_iter()
                .flatten()
                .filter_map(Value::as_str)
                .collect();
            let target_name = target["name"].as_str().unwrap_or_default().to_owned();
            if kinds.contains(&"lib") {
                lib = Some(target_name);
            } else if kinds.contains(&"bin") {
                bins.push(target_name);
            }
        }
        bins.sort();
        found.push(Package {
            name,
            directory,
            lib,
            bins,
            description: description.trim().to_owned(),
        });
    }
    if found.is_empty() {
        return Err("cargo metadata lists no packages".to_owned());
    }
    found.sort_by(|a, b| a.name.cmp(&b.name));
    Ok(found)
}

fn table(packages: &[&Package]) -> String {
    let mut out =
        String::from("| Package | Directory | In Rust | What it is |\n|---|---|---|---|\n");
    for package in packages {
        let mut uses = Vec::new();
        if let Some(lib) = &package.lib {
            uses.push(format!("`use {lib}`"));
        }
        for bin in &package.bins {
            uses.push(format!("binary `{bin}`"));
        }
        out.push_str(&format!(
            "| `{}` | [`{dir}`]({TREE}/{dir}) | {} | {} |\n",
            package.name,
            uses.join(", "),
            cell(&package.description),
            dir = package.directory,
        ));
    }
    out
}

/// The crate list page for the packages of `metadata`.
fn page_for(metadata: &Value) -> Result<String> {
    let all = packages(metadata)?;
    let of = |wanted: Group| -> Vec<&Package> {
        all.iter()
            .filter(|package| group(package) == wanted)
            .collect()
    };
    let mut out = front_matter(
        "Crates",
        "Crates",
        "Every package of the Connectors workspace, generated from cargo metadata.",
        2,
    );
    out.push_str(&format!(
        "# Crates\n\nGenerated by `connectors-docs` from `cargo metadata --no-deps`: every package of the workspace, with the `description` its `Cargo.toml` gives. There are {} packages. None is on a registry; build them from the source checkout. The generated CLI parser, `apps/connectors-cli-contract`, is a path dependency of `connectors` outside the workspace and is regenerated by `connectors-build cli`, never edited.\n\n## Libraries and the command line\n\nThe shared boundary an application, an adapter or a host builds on, and the `connectors` command.\n\n{}\n## Adapters\n\nEach adapter owns its provider behaviour and builds a standalone executable. With `--no-default-features` the library alone depends on no host, client or sibling adapter; the repository gate holds that boundary.\n\n{}\n## Repository tooling\n\nGenerators, checks and acceptance runners the repository's own gate and maintainers use. Nothing outside the repository depends on them.\n\n{}",
        all.len(),
        table(&of(Group::Application)),
        table(&of(Group::Adapter)),
        table(&of(Group::Tooling)),
    ));
    Ok(out)
}

/// The crate list page for the workspace at `root`, read with `cargo metadata`.
pub fn page(root: &Path) -> Result<String> {
    let cargo = std::env::var_os("CARGO").unwrap_or_else(|| "cargo".into());
    let output = Command::new(&cargo)
        .args([
            "metadata",
            "--no-deps",
            "--format-version",
            "1",
            "--offline",
            "--manifest-path",
        ])
        .arg(root.join("Cargo.toml"))
        .output()
        .map_err(|error| format!("running cargo metadata: {error}"))?;
    if !output.status.success() {
        return Err(format!(
            "cargo metadata failed: {}",
            String::from_utf8_lossy(&output.stderr)
        ));
    }
    let metadata: Value = serde_json::from_slice(&output.stdout)
        .map_err(|error| format!("parsing cargo metadata: {error}"))?;
    page_for(&metadata)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn metadata(description: Option<&str>) -> Value {
        serde_json::json!({
            "workspace_root": "/w",
            "packages": [
                {
                    "name": "connectors-docs",
                    "manifest_path": "/w/crates/connectors-docs/Cargo.toml",
                    "description": "Generates pages.",
                    "targets": [{"kind": ["bin"], "name": "connectors-docs"}]
                },
                {
                    "name": "connectors-sql",
                    "manifest_path": "/w/adapters/sql/Cargo.toml",
                    "description": "Reads | rows.",
                    "targets": [
                        {"kind": ["lib"], "name": "connectors_sql"},
                        {"kind": ["bin"], "name": "connectors-sql"},
                        {"kind": ["test"], "name": "protocol"}
                    ]
                },
                {
                    "name": "connectors-core",
                    "manifest_path": "/w/crates/connectors-core/Cargo.toml",
                    "description": description,
                    "targets": [{"kind": ["lib"], "name": "connectors_core"}]
                }
            ]
        })
    }

    #[test]
    fn packages_are_grouped_and_linked() {
        let page = page_for(&metadata(Some("Wire contracts."))).unwrap();
        assert!(page.contains("# generated by connectors-docs, do not edit"));
        assert!(page.contains("There are 3 packages."));
        let libraries = page.find("## Libraries").unwrap();
        let core = page.find("| `connectors-core` |").unwrap();
        let adapters = page.find("## Adapters").unwrap();
        let sql = page.find("| `connectors-sql` |").unwrap();
        let tooling = page.find("## Repository tooling").unwrap();
        let docs = page.find("| `connectors-docs` |").unwrap();
        assert!(
            libraries < core
                && core < adapters
                && adapters < sql
                && sql < tooling
                && tooling < docs
        );
        assert!(page.contains(
            "| `connectors-sql` | [`adapters/sql`](https://github.com/beyond10x/connectors/tree/main/adapters/sql) | `use connectors_sql`, binary `connectors-sql` | Reads \\| rows. |"
        ));
    }

    #[test]
    fn a_package_without_a_description_is_refused() {
        assert!(page_for(&metadata(None)).is_err());
    }
}
