//! Generates the derivable pages of the Connectors documentation site, checks them for drift,
//! and binds a built site to its source commit. The site build itself is Docusaurus.
//!
//! `generate` writes:
//!
//! - `website/docs/reference/cli.md`, walked from the clap definitions the `connectors` binary
//!   parses ([`cli`]);
//! - `website/docs/reference/crates.md`, from `cargo metadata --no-deps` ([`crates`]);
//! - the contract and model reference under `website/docs/reference/` ([`reference`]): every
//!   contract `website/publication.json` selects, rendered from its owner's Markdown, and every
//!   selected ESS model, from the pinned `ess generate --kind docs`;
//! - `website/data/status.json` (`b10x-status/1`) and `website/docs/status.md` ([`status`]), where
//!   every shipped capability names the test that holds it and generation fails when that test is
//!   gone.
//!
//! `generate --check` writes nothing and fails on a missing, stale, hand-edited or orphaned
//! generated file. Both also check every page ([`pages`]): front matter, bracketed admonition
//! titles and the passive Markdown the unified documentation site accepts.
//!
//! `provenance` writes `.well-known/b10x-site.json` and the route inventory
//! `.well-known/b10x-routes.json` into a built site ([`routes`]).

mod cli;
mod crates;
mod markdown;
mod pages;
mod reference;
mod routes;
mod status;

use std::{
    collections::BTreeMap,
    fs,
    path::{Path, PathBuf},
    process::ExitCode,
};

use clap::{Parser, Subcommand};

/// Every failure is reported as one message and exit code 1.
type Result<T> = std::result::Result<T, String>;

/// The first line of every generated page's front matter.
const FRONT_MATTER_HEADER: &str = "# generated by connectors-docs, do not edit";
/// A file in the repository on GitHub, by path.
const SOURCE: &str = "https://github.com/beyond10x/connectors/blob/main";
/// Every documentation page, relative to the repository root.
const DOCS: &str = "website/docs";

#[derive(Parser)]
#[command(about = "Generate and check the derived pages of the Connectors documentation site")]
struct Cli {
    #[command(subcommand)]
    command: Action,
}

#[derive(Subcommand)]
enum Action {
    /// Regenerate the reference pages and the status page and data, or check them for drift.
    Generate {
        /// Write nothing; fail when a generated file is missing, stale, hand-edited or orphaned.
        #[arg(long)]
        check: bool,
        /// Repository root.
        #[arg(long, default_value = ".")]
        root: PathBuf,
        /// The pinned `ess` executable; otherwise `CONNECTORS_ESS`, then `ess` on PATH.
        #[arg(long)]
        ess: Option<PathBuf>,
    },
    /// Bind a built site to its source commit: write `.well-known/b10x-site.json` and the route
    /// inventory `.well-known/b10x-routes.json` into it.
    Provenance {
        /// The built site, `website/build`.
        #[arg(long)]
        site: PathBuf,
        /// The full Git revision the site was built from.
        #[arg(long)]
        commit: String,
    },
}

/// Generated files keyed by their path relative to the repository root.
type Outputs = BTreeMap<String, String>;

fn outputs(root: &Path, ess: &Path) -> Result<Outputs> {
    let mut outputs = Outputs::new();
    outputs.insert(cli::PAGE.to_owned(), cli::page());
    outputs.insert(crates::PAGE.to_owned(), crates::page(root)?);
    outputs.insert(status::DATA.to_owned(), status::data(root)?);
    outputs.insert(status::PAGE.to_owned(), status::page(root)?);
    for (relative, content) in reference::outputs(root, ess)? {
        if outputs.insert(relative.clone(), content).is_some() {
            return Err(format!("{relative} is generated twice"));
        }
    }
    Ok(outputs)
}

/// The drift of one generated file: `None` when it is current.
fn drift(root: &Path, relative: &str, expected: &str) -> Option<String> {
    match fs::read_to_string(root.join(relative)) {
        Err(_) => Some(format!("missing {relative}")),
        Ok(found) if found != expected => Some(format!("stale or edited {relative}")),
        Ok(_) => None,
    }
}

fn generate(root: &Path, ess: &Path, check: bool) -> Result<()> {
    let outputs = outputs(root, ess)?;
    let orphans = reference::orphans(root, &outputs)?;
    if check {
        let mut problems: Vec<_> = outputs
            .iter()
            .filter_map(|(relative, content)| drift(root, relative, content))
            .collect();
        problems.extend(
            orphans
                .iter()
                .map(|relative| format!("orphaned {relative}")),
        );
        if !problems.is_empty() {
            return Err(format!(
                "generated files have drifted ({}); run `cargo run --locked -p connectors-docs -- generate`",
                problems.join(", ")
            ));
        }
        println!("{} generated files: current", outputs.len());
    } else {
        for relative in &orphans {
            fs::remove_file(root.join(relative))
                .map_err(|error| format!("removing {relative}: {error}"))?;
            println!("{relative}: removed");
        }
        let mut written = 0;
        for (relative, content) in &outputs {
            if drift(root, relative, content).is_none() {
                continue;
            }
            let path = root.join(relative);
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent)
                    .map_err(|error| format!("creating {}: {error}", parent.display()))?;
            }
            fs::write(&path, content).map_err(|error| format!("writing {relative}: {error}"))?;
            println!("{relative}: written");
            written += 1;
        }
        println!("{} generated files, {written} written", outputs.len());
    }
    let problems = pages::check(root)?;
    if !problems.is_empty() {
        return Err(format!(
            "documentation pages fail their checks:\n  {}",
            problems.join("\n  ")
        ));
    }
    println!("{DOCS}: front matter, admonition titles and passive Markdown checked");
    Ok(())
}

/// The project-site publication record for one build of the `/connectors/` site.
fn site_manifest(commit: &str) -> Result<String> {
    if commit.len() != 40
        || !commit.bytes().all(|b| b.is_ascii_hexdigit())
        || commit.bytes().all(|b| b == b'0')
    {
        return Err("commit must be a nonzero full Git revision".to_owned());
    }
    Ok(format!(
        "{{\n  \"baseUrl\": \"{}\",\n  \"commit\": \"{commit}\",\n  \"repository\": \"connectors\",\n  \"schema\": \"b10x-project-site/v1\"\n}}",
        routes::BASE
    ))
}

fn write_provenance(site: &Path, commit: &str) -> Result<()> {
    let manifest = site_manifest(commit)?;
    if !site.join("index.html").is_file() {
        return Err(format!("{} holds no built site", site.display()));
    }
    let write = |path: PathBuf, content: &str| {
        fs::write(&path, content).map_err(|error| format!("writing {}: {error}", path.display()))
    };
    fs::create_dir_all(site.join(".well-known"))
        .map_err(|error| format!("creating .well-known: {error}"))?;
    let inventory = routes::inventory(site, commit)?;
    write(site.join(".well-known/b10x-site.json"), &manifest)?;
    write(site.join(".well-known/b10x-routes.json"), &inventory)?;
    write(site.join(".nojekyll"), "")
}

/// The pinned `ess`, resolved as every repository tool resolves it.
fn ess(requested: Option<&Path>) -> Result<PathBuf> {
    let ess = connectors_spec::toolchain::resolve(requested).map_err(|error| error.to_string())?;
    connectors_spec::toolchain::check(&ess).map_err(|error| error.to_string())?;
    Ok(ess)
}

fn main() -> ExitCode {
    let result = match Cli::parse().command {
        Action::Generate {
            check,
            root,
            ess: requested,
        } => ess(requested.as_deref()).and_then(|ess| {
            let root = root
                .canonicalize()
                .map_err(|error| format!("{}: {error}", root.display()))?;
            generate(&root, &ess, check)
        }),
        Action::Provenance { site, commit } => write_provenance(&site, &commit)
            .map(|()| println!("{}: bound to {commit}", site.display())),
    };
    match result {
        Ok(()) => ExitCode::SUCCESS,
        Err(message) => {
            eprintln!("connectors-docs: {message}");
            ExitCode::FAILURE
        }
    }
}

/// Quote a value as a YAML double-quoted scalar.
fn yaml_string(value: &str) -> String {
    format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
}

/// `value` as one Markdown table cell: on one line, with `|` escaped.
fn cell(value: &str) -> String {
    value
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
        .replace('|', "\\|")
}

/// The front matter of a generated page: the generator line, title, label, sidebar position,
/// description and no edit link.
fn front_matter(title: &str, label: &str, description: &str, position: usize) -> String {
    format!(
        "---\n{FRONT_MATTER_HEADER}\ntitle: {}\nsidebar_label: {}\nsidebar_position: {position}\ndescription: {}\ncustom_edit_url: null\n---\n\n",
        yaml_string(title),
        yaml_string(label),
        yaml_string(description),
    )
}

/// The repository root, for tests.
#[cfg(test)]
fn repository_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .expect("repository root")
}

/// A fresh scratch directory under the system temporary directory, for tests.
#[cfg(test)]
fn scratch(name: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!("connectors-docs-{name}-{}", std::process::id()));
    let _ = fs::remove_dir_all(&dir);
    fs::create_dir_all(&dir).expect("scratch directory");
    dir
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn provenance_refuses_anything_but_a_full_nonzero_revision() {
        let commit = "e86f43d90b637fc2c1790f77d59efff2eb852386";
        let manifest = site_manifest(commit).unwrap();
        assert!(manifest.contains(&format!("\"commit\": \"{commit}\"")));
        assert!(manifest.contains("\"baseUrl\": \"/connectors/\""));
        assert!(manifest.contains("\"repository\": \"connectors\""));
        assert!(manifest.contains("\"schema\": \"b10x-project-site/v1\""));
        for bad in [
            "e86f43d",
            &"0".repeat(40),
            &format!("{}\"", &commit[..39]),
            &format!("{commit}0"),
        ] {
            assert!(site_manifest(bad).is_err(), "{bad}");
        }
    }

    #[test]
    fn provenance_writes_both_documents_into_a_built_site_only() {
        let commit = "e86f43d90b637fc2c1790f77d59efff2eb852386";
        let site = scratch("provenance");
        assert!(write_provenance(&site, commit).is_err());
        fs::write(site.join("index.html"), r#"<main id="main">"#).unwrap();
        write_provenance(&site, commit).unwrap();
        let manifest = fs::read_to_string(site.join(".well-known/b10x-site.json")).unwrap();
        assert_eq!(manifest, site_manifest(commit).unwrap());
        let routes = fs::read_to_string(site.join(".well-known/b10x-routes.json")).unwrap();
        assert!(routes.contains("\"path\": \"/connectors/\""));
        assert!(site.join(".nojekyll").is_file());
        fs::remove_dir_all(site).unwrap();
    }

    #[test]
    fn yaml_strings_escape_quotes_and_backslashes() {
        assert_eq!(yaml_string(r#"a "b" \c"#), r#""a \"b\" \\c""#);
    }

    /// The pages in this tree are what `generate` writes from this tree's sources, and no
    /// generated directory holds a file `generate` would not write.
    #[test]
    fn every_generated_file_is_current_in_this_tree() {
        let root = repository_root();
        let ess = ess(None).expect("the pinned ess release");
        let outputs = outputs(&root, &ess).unwrap();
        for (relative, content) in &outputs {
            let found = fs::read_to_string(root.join(relative))
                .unwrap_or_else(|_| panic!("{relative} is missing; run connectors-docs generate"));
            assert!(
                &found == content,
                "{relative} is stale; run connectors-docs generate"
            );
        }
        assert_eq!(
            reference::orphans(&root, &outputs).unwrap(),
            Vec::<String>::new()
        );
    }

    #[test]
    fn every_documentation_page_passes_its_checks() {
        let problems = pages::check(&repository_root()).unwrap();
        assert!(problems.is_empty(), "{problems:#?}");
    }
}
